[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "food_delivery_gym"
version = "1.1.0"
dependencies = [
  "simpy",
  "matplotlib",
  "pygame",
  "gymnasium",
  "numpy"
]